### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by rakshazi** [mishak87/atom-build-dockerfile#1]
Hello!
OS: Ubuntu 16.04
Editor: Atom 1.7.2
Atom Build installed, but when i try to show build targets (F7), "No target builds" message shows.
What i doing wrong?

**Comment by mishak87** [comment]
Hi I'll check other projects for reference if I did something 1.8 specific.

It [works in 1.8 beta](https://cloud.githubusercontent.com/assets/276500/14828375/09b7e43e-0be7-11e6-99b2-8a301844a53d.png) which I am using most of time.

**Comment by mishak87** [comment]
**Hacked: Always on for 1.7.***

I have 1.7.0 so please confirm it works for you otherwise I will have to download 1.7.2 :smile:.

---

My use-case for this plugin was to run `docker build -f <dockerfile> $(basename <dockerfile>)` for active editor using single key.

Proper fix would require scaning project for all available Dockerfiles.

[atom-build-markdown](https://github.com/bwinton/atom-build-markdown/blob/master/lib/markdown.js) plugin I was using as reference when writing this one does not work on 1.7 too.

**Comment by rakshazi** [comment]
oh, i'll upgrade than to newer editor version.
Please, add info about this problem on 1.7.x to readme
thanks for help!

**Comment by mishak87** [comment]
Thanks for reporting this. I have updated the readme.
